// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414233030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Ciudad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("api.Models.Departamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("api.Models.ModelosCoordinado", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoStdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_std_min");

                    b.HasKey("id");

                    b.ToTable("modelos_coordinado", (string)null);
                });

            modelBuilder.Entity("api.Models.ModelosCorte", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoForro")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_forro");

                    b.Property<decimal?>("tiempoLoteo")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_loteo");

                    b.Property<decimal?>("tiempoPiel")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_piel");

                    b.HasKey("id");

                    b.ToTable("modelos_corte", (string)null);
                });

            modelBuilder.Entity("api.Models.ModelosMontado", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoStdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_std_min");

                    b.HasKey("id");

                    b.ToTable("modelos_montado", (string)null);
                });

            modelBuilder.Entity("api.Models.ModelosPespunte", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoStdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_std_min");

                    b.HasKey("id");

                    b.ToTable("modelos_pespunte", (string)null);
                });

            modelBuilder.Entity("api.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDePares")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_pares");

                    b.Property<DateTime>("FechaDePedido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_pedido");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<int>("Idcliente")
                        .HasColumnType("integer")
                        .HasColumnName("idcliente");

                    b.HasKey("Id");

                    b.HasIndex("Idcliente");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("api.Models.PedidoDetalleNumeracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<int>("Talla")
                        .HasColumnType("integer")
                        .HasColumnName("talla");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("pedido_detalle_numeracion", (string)null);
                });

            modelBuilder.Entity("api.Models.Ciudad", b =>
                {
                    b.HasOne("api.Models.Departamento", "Departamento")
                        .WithMany("ciudades")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("api.Models.Pedido", b =>
                {
                    b.HasOne("api.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("Idcliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("api.Models.PedidoDetalleNumeracion", b =>
                {
                    b.HasOne("api.Models.Pedido", "Pedido")
                        .WithMany("DetallesNumeracion")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("api.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("api.Models.Departamento", b =>
                {
                    b.Navigation("ciudades");
                });

            modelBuilder.Entity("api.Models.Pedido", b =>
                {
                    b.Navigation("DetallesNumeracion");
                });
#pragma warning restore 612, 618
        }
    }
}
