// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604213318_AddActualizaciónProgramación5")]
    partial class AddActualizaciónProgramación5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Ciudad", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CiudadId"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("CiudadId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("ciudades", (string)null);
                });

            modelBuilder.Entity("api.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Nombre");

                    b.HasKey("ClienteId");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("api.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartamentoId"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("DepartamentoId");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("api.Models.Modelos.ModelosCoordinado", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoStdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_std_min");

                    b.HasKey("id");

                    b.ToTable("modelos_coordinado", (string)null);
                });

            modelBuilder.Entity("api.Models.Modelos.ModelosCorte", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoForro")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_forro");

                    b.Property<decimal?>("tiempoLoteo")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_loteo");

                    b.Property<decimal?>("tiempoPiel")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_piel");

                    b.Property<decimal?>("tiempoStdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_std_min");

                    b.HasKey("id");

                    b.ToTable("modelos_corte", (string)null);
                });

            modelBuilder.Entity("api.Models.Modelos.ModelosInyeccion", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoStdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_std_min");

                    b.HasKey("id");

                    b.ToTable("modelos_inyeccion", (string)null);
                });

            modelBuilder.Entity("api.Models.Modelos.ModelosMontado", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoStdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_std_min");

                    b.HasKey("id");

                    b.ToTable("modelos_montado", (string)null);
                });

            modelBuilder.Entity("api.Models.Modelos.ModelosPespunte", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoStdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_std_min");

                    b.HasKey("id");

                    b.ToTable("modelos_pespunte", (string)null);
                });

            modelBuilder.Entity("api.Models.Modelos.ModelosPlantilla", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoStdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_std_min");

                    b.HasKey("id");

                    b.ToTable("modelos_plantilla", (string)null);
                });

            modelBuilder.Entity("api.Models.Modelos.ModelosPreacabado", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("estilo")
                        .HasColumnType("text")
                        .HasColumnName("estilo");

                    b.Property<string>("linea")
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("proceso")
                        .HasColumnType("text")
                        .HasColumnName("proceso");

                    b.Property<decimal?>("tiempoStdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_std_min");

                    b.HasKey("id");

                    b.ToTable("modelos_preacabado", (string)null);
                });

            modelBuilder.Entity("api.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDePares")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_pares");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("idcliente");

                    b.Property<string>("Coleccion")
                        .HasColumnType("text")
                        .HasColumnName("coleccion");

                    b.Property<string>("ColorBigZap")
                        .HasColumnType("text")
                        .HasColumnName("color_big_zap");

                    b.Property<string>("Construccion")
                        .HasColumnType("text")
                        .HasColumnName("construccion");

                    b.Property<DateTime>("FechaDePedido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_pedido");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<DateTime?>("FechaLiberacionExplosion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_liberacion_explosion");

                    b.Property<DateTime?>("FechaRealizacionExplosion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_realizacion_explosion");

                    b.Property<string>("Modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("PedidoCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pedido_cliente");

                    b.Property<int?>("PedidoInterno")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_interno");

                    b.Property<string>("Piel")
                        .HasColumnType("text")
                        .HasColumnName("piel");

                    b.Property<string>("SemanaFolioExplosion")
                        .HasColumnType("text")
                        .HasColumnName("semana_folio_explosion");

                    b.Property<string>("SemanaProgramada")
                        .HasColumnType("text")
                        .HasColumnName("semana_programada");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("api.Models.PedidoDetalleNumeracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<int?>("ProgramacionidPedido")
                        .HasColumnType("integer");

                    b.Property<int>("Talla")
                        .HasColumnType("integer")
                        .HasColumnName("talla");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProgramacionidPedido");

                    b.ToTable("pedido_detalle_numeracion", (string)null);
                });

            modelBuilder.Entity("api.Models.Programacion", b =>
                {
                    b.Property<int>("idPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idpedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPedido"));

                    b.Property<int?>("CiudadId")
                        .HasColumnType("integer")
                        .HasColumnName("Ciudadid");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("ClienteId");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("Departamentoid");

                    b.Property<int>("capacidadDia")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_dia");

                    b.Property<int>("capacidadReal")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_real");

                    b.Property<int>("cargaDia")
                        .HasColumnType("integer")
                        .HasColumnName("carga_dia");

                    b.Property<int>("deficit")
                        .HasColumnType("integer")
                        .HasColumnName("deficit");

                    b.Property<int>("demandaDia")
                        .HasColumnType("integer")
                        .HasColumnName("demanda_dia");

                    b.Property<string>("dia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dia");

                    b.Property<string>("linea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("linea");

                    b.Property<int>("minutosDispo")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_dispo");

                    b.Property<int>("modelo")
                        .HasColumnType("integer")
                        .HasColumnName("modelo");

                    b.Property<int>("personal")
                        .HasColumnType("integer")
                        .HasColumnName("personal");

                    b.Property<int>("programacionIdeal")
                        .HasColumnType("integer")
                        .HasColumnName("programacion_ideal");

                    b.Property<decimal>("saturacion")
                        .HasColumnType("numeric")
                        .HasColumnName("saturacion");

                    b.Property<int>("semana")
                        .HasColumnType("integer")
                        .HasColumnName("semana");

                    b.Property<decimal>("tiempoEst")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_est");

                    b.HasKey("idPedido");

                    b.HasIndex("CiudadId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("programacion", (string)null);
                });

            modelBuilder.Entity("api.Models.Ciudad", b =>
                {
                    b.HasOne("api.Models.Departamento", "Departamento")
                        .WithMany("ciudades")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("api.Models.Pedido", b =>
                {
                    b.HasOne("api.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("api.Models.PedidoDetalleNumeracion", b =>
                {
                    b.HasOne("api.Models.Pedido", "Pedido")
                        .WithMany("DetallesNumeracion")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Programacion", null)
                        .WithMany("DetallesNumeracion")
                        .HasForeignKey("ProgramacionidPedido");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("api.Models.Programacion", b =>
                {
                    b.HasOne("api.Models.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId");

                    b.HasOne("api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("api.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.Navigation("Ciudad");

                    b.Navigation("Cliente");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("api.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("api.Models.Departamento", b =>
                {
                    b.Navigation("ciudades");
                });

            modelBuilder.Entity("api.Models.Pedido", b =>
                {
                    b.Navigation("DetallesNumeracion");
                });

            modelBuilder.Entity("api.Models.Programacion", b =>
                {
                    b.Navigation("DetallesNumeracion");
                });
#pragma warning restore 612, 618
        }
    }
}
